### ISSUE TITLE
Create ACLs

### ISSUE THREAD

**Issue by Freddyreza53** [esolutionsone/timesheet-app#72]
to prevent anyone seeing things that dont belong to them

--Nick Edit--
We'll need to implement roles, too: delivery_consultant, delivery_admin

- [x] Consultant Read: only timestamps and entries associated with their consultantId
- [ ] Consultant Read: select fields from one_core tables
- [x] Consultant Write: timestamp and time_entry table
- [x] Consultant Update: only time_entry records in 'draft' state

Questions:
- How best to allow the user to dotwalk to the info they need (on REST Queries) but be able to dot-walk to things like project_budget?

**Comment by blingusblongus** [comment]
We'll need to implement roles, too: delivery_consultant, delivery_admin

- [ ] Consultant Read: only timestamps and entries associated with their consultantId
- [ ] Consultant Read: select fields from one_core tables
- [ ] Consultant Write: timestamp and time_entry table
- [ ] Consultant Update: only time_entry records in 'draft' state

Questions:
- How best to allow the user to dotwalk to the info they need (on REST Queries) but be able to dot-walk to things like project_budget?
